import express from "express";
import cors from "cors";
import { chromium } from "playwright";
import fs from "fs";
import path from "path";

const css = fs.readFileSync(
  path.join(process.cwd(), "report.css"),
  "utf8"
);

const app = express();

app.use(cors({
  origin: "*",
  methods: ["POST"],
}));

app.use(express.json());

function buildReportHTML({
  monthLabel,
  total,
  categories,
  transactions = []   // 👈 ADD THIS
}) {

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    ${css}
  </style>
</head>

<body>

  <!-- PAGE 1 -->
  <div class="page">
    <div class="content">
      <h1>Monthly Expense Report</h1>
      <div class="sub">${monthLabel}</div>

      <div class="summary">
        <div class="summary-label">Total Expenses</div>
        <div class="summary-value">
          <span class="currency">₱</span>
          ${Number(total).toLocaleString(undefined, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
          })}
        </div>
      </div>

      <div class="section">
        <h3>Category Breakdown</h3>
        <table>
          <tr>
            <th>Category</th>
            <th style="text-align:right">Amount</th>
          </tr>
          ${categories.map(c => `
            <tr>
              <td>${c.name}</td>
              <td class="amount">
                ₱${Number(c.amount).toLocaleString(undefined, {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2
                })}
              </td>
            </tr>
          `).join("")}
        </table>
      </div>

      <div class="footer">
        Generated by Spendr · ${new Date().toLocaleDateString()}
      </div>
    </div>
  </div>

  <!-- PAGE 2 -->
  <div class="page">
    <div class="content">
      <h2>All Transactions</h2>
      <div class="sub">${monthLabel}</div>

      <table class="transactions">
        <tr>
          <th style="width:15%">Date</th>
          <th>Description</th>
          <th style="width:20%">Category</th>
          <th style="width:20%">Payment</th>
          <th style="width:15%; text-align:right">Amount</th>
        </tr>

        ${transactions.map(t => `
          <tr>
            <td>${t.date}</td>
            <td>${t.description}</td>
            <td>${t.category}</td>
            <td>${t.payment}</td>
            <td class="amount">
              ₱${Number(t.amount).toLocaleString(undefined, {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2
              })}
            </td>
          </tr>
        `).join("")}
      </table>
    </div>
  </div>

</body>

</html>
`;
}


app.post("/generate-pdf", async (req, res) => {
  try {
    const html = buildReportHTML(req.body);

    const browser = await chromium.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process"
      ]
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "0mm",
        right: "0mm",
        bottom: "0mm",
        left: "0mm"
      }
    });



    await browser.close();

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=report.pdf",
      "Content-Length": pdf.length
    });


    res.send(pdf);
  } catch (err) {
    console.error(err);
    res.status(500).send("PDF generation failed");
  }
});

app.post("/preview-report", (req, res) => {
  try {
    const html = buildReportHTML(req.body);
    res.setHeader("Content-Type", "text/html");
    res.send(html);
  } catch (err) {
    console.error("PREVIEW ERROR:", err);
    res.status(500).send("Preview failed");
  }
});


const PORT = process.env.PORT || 8080;

app.listen(PORT, () => {
  console.log("PDF service listening on", PORT);
});
